FROM node:20-slim AS build

WORKDIR /app

ARG VITE_SUPABASE_URL
ARG VITE_SUPABASE_KEY

COPY web/package.json web/bun.lockb* ./
RUN npm install

COPY web/ .

ENV VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
ENV VITE_SUPABASE_KEY=${VITE_SUPABASE_KEY}

RUN npm run build

FROM nginx:alpine

COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
